import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import dev from '../public/dev-ed-wave.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hasibul Hasan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white  px-10">
        <section className=" min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-burtons">Portfolio</h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill className=" cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="font-burtons bg-gradient-to-r from-cyan-600 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 font-medium"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium">
              Hasibul Hasan
            </h2>
            <h3 className=" text-2xl py-2">Software Developer</h3>
            <p className=" text-base py-2 leading-7 text-gray-800">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
          </div>

          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>

          <div className=" mx-auto bg-gradient-to-b from-teal-600 rounded-full w-80 h-80 relative overflow-hidden mt-20">
            <Image src={dev} layout="fill" objectFit="cover" alt="avatar" />
          </div>
        </section>
        
        <section>

        </section>
      </main>
    </div>
  );
}
